trigger: none

resources:
  repositories:
    - repository: SharedTemplates
      type: git
      name: SharedTemplates

stages:
  - template: D365/extract.yml@SharedTemplates
    parameters:
      solution: base
